INSERT INTO trainLine (name, companyID) VALUES ('山手線', (SELECT id FROM company WHERE name = 'JR') );

INSERT INTO station (name) VALUES ('東京');
INSERT INTO station (name) VALUES ('有楽町');
INSERT INTO station (name) VALUES ('新橋');
INSERT INTO station (name) VALUES ('浜松町');
INSERT INTO station (name) VALUES ('田町');
INSERT INTO station (name) VALUES ('品川');
INSERT INTO station (name) VALUES ('大崎');
INSERT INTO station (name) VALUES ('五反田');
INSERT INTO station (name) VALUES ('目黒');
INSERT INTO station (name) VALUES ('恵比寿');
INSERT INTO station (name) VALUES ('渋谷');
INSERT INTO station (name) VALUES ('原宿');
INSERT INTO station (name) VALUES ('代々木');
INSERT INTO station (name) VALUES ('新宿');
INSERT INTO station (name) VALUES ('新大久保');
INSERT INTO station (name) VALUES ('高田馬場');
INSERT INTO station (name) VALUES ('目白');
INSERT INTO station (name) VALUES ('池袋');
INSERT INTO station (name) VALUES ('大塚');
INSERT INTO station (name) VALUES ('巣鴨');
INSERT INTO station (name) VALUES ('駒込');
INSERT INTO station (name) VALUES ('田端');
INSERT INTO station (name) VALUES ('西日暮里');
INSERT INTO station (name) VALUES ('日暮里');
INSERT INTO station (name) VALUES ('鶯谷');
INSERT INTO station (name) VALUES ('上野');
INSERT INTO station (name) VALUES ('御徒町');
INSERT INTO station (name) VALUES ('秋葉原');
INSERT INTO station (name) VALUES ('神田');

INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '東京'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '有楽町'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '新橋'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '浜松町'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '田町'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '品川'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '大崎'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '五反田'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '目黒'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '恵比寿'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '渋谷'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '原宿'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '代々木'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '新宿'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '新大久保'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '高田馬場'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '目白'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '池袋'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '大塚'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '巣鴨'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '駒込'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '田端'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '西日暮里'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '日暮里'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '鶯谷'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '上野'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '御徒町'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '秋葉原'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '山手線'), (SELECT id FROM station WHERE name = '神田'));
