
INSERT INTO trainLine (name, companyID) VALUES ('有楽町線', (SELECT id FROM company WHERE name = '東京メトロ') );

INSERT INTO station (name) VALUES ('和光市');
INSERT INTO station (name) VALUES ('地下鉄成増');
INSERT INTO station (name) VALUES ('地下鉄赤塚');
INSERT INTO station (name) VALUES ('平和台');
INSERT INTO station (name) VALUES ('氷川台');
INSERT INTO station (name) VALUES ('小竹向原');
INSERT INTO station (name) VALUES ('千川');
INSERT INTO station (name) VALUES ('要町');
INSERT INTO station (name) VALUES ('池袋');
INSERT INTO station (name) VALUES ('東池袋');
INSERT INTO station (name) VALUES ('護国寺');
INSERT INTO station (name) VALUES ('江戸川橋');
INSERT INTO station (name) VALUES ('飯田橋');
INSERT INTO station (name) VALUES ('市ヶ谷');
INSERT INTO station (name) VALUES ('麹町');
INSERT INTO station (name) VALUES ('永田町');
INSERT INTO station (name) VALUES ('桜田門');
INSERT INTO station (name) VALUES ('有楽町');
INSERT INTO station (name) VALUES ('銀座一丁目');
INSERT INTO station (name) VALUES ('新富町');
INSERT INTO station (name) VALUES ('月島');
INSERT INTO station (name) VALUES ('豊洲');
INSERT INTO station (name) VALUES ('辰巳');
INSERT INTO station (name) VALUES ('新木場');

INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '和光市'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '地下鉄成増'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '地下鉄赤塚'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '平和台'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '氷川台'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '小竹向原'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '千川'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '要町'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '池袋'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '東池袋'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '護国寺'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '江戸川橋'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '飯田橋'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '市ヶ谷'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '麹町'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '永田町'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '桜田門'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '有楽町'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '銀座一丁目'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '新富町'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '月島'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '豊洲'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '辰巳'));
INSERT INTO trainLineStation (trainLineID,StationID) VALUES ((SELECT id FROM trainLine WHERE name = '有楽町線'), (SELECT id FROM station WHERE name = '新木場'));
